name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run add_friend tests
      run: python -m unittest src/unit_tests/test_add_friend.py

    - name: Run remove_friend tests
      run: python -m unittest src/unit_tests/test_remove_friend.py

    - name: Run search_user tests
      run: python -m unittest src/unit_tests/test_search_user.py